# Generated by Django 4.2 on 2026-03-06 08:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAISSDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(db_index=True, max_length=128, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('page_count', models.IntegerField(default=0)),
                ('chunk_count', models.IntegerField(default=0)),
                ('index_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=api.models.default_expiry)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
