# Generated by Django 4.2 on 2026-03-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faissdocument',
            name='file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
